docusaurus.config.js

* change docs url to /knowledge

---

docusaurus.config.js
package.json

* Add google analytics 4 tracking

---

docs/04-terminology.md

updated urls for terminology

---

docs/fundamentals/enrollment-member-months.md

This is the initial commit for knowledge base on member months. It has a few basic queries and data quality issues. Additional analysis will be added for more in depth churn analysis and examples for data quality issues.

initial commit of the enrollment and member months knowledge base post

---

docs/claims-data-warehouse/setup.md

testing redeployment with redirect

arbitrary change to re-force deployment

---

static/data/terminology.csv

There were a few broken links in the terminology catalog - I removed these.

fixed broken links in terminology catalog

---

docs/claims-data-model/about.md
docs/claims-data-model/data-dictionary/medical-claim.md
docs/claims-data-model/data-dictionary/pharmacy-claim.md
docs/data-marts/pmpm/data-dictionary/pmpm.md
sidebars.js

- Added claims data model section that includes a data dictionary and mapping guide
- Updated Acute Inpatient data dictionary and PMPM data dictionary

Claims data model

---

docs/getting-started/quickstart.md

Updated supported dbt versions to `1.3.X or greater.`

Update supported dbt version in quickstart.md

---

docs/getting-started/contributing.md
sidebars.js

* Added a new "Contributing" page to the Getting Started section.

Add contribution guide

---

docs/data-marts/cms-hcc/about.md
docs/data-marts/cms-hcc/example-sql.md
sidebars.js

* Updated the docs page for CMS HCC mart
* Added SQL examples for CMS HCC

Update docs for the CMS HCC mart

---

docs/claims-data-model/data-dictionary/eligibility.md
docs/claims-data-model/data-dictionary/medical-claim.md
docs/claims-data-model/data-dictionary/pharmacy-claim.md
docs/data-marts/ccsr/data-dictionary/wide-condition-category.md
docs/data-marts/ccsr/data-dictionary/wide-procedure-category.md
docs/data-marts/core/data-dictionary/practitioner.md
docs/data-marts/input-layer/data-dictionary/eligibility.md
docs/data-marts/member-months/data-dictionary/member-months.md
docs/data-marts/pmpm/data-dictionary/pmpm-prep.md
docs/data-marts/pmpm/data-dictionary/pmpm.md
sidebars.js
src/components/JsonDataTable.js

repointed models whos resource path had been moved to the correct path
renamed provider to practitioner
added contect for ccsr wide tables

Model updates

---

docs/example-sql.md

updated column in `Volume and Average Cost of Encounters by Type` query

updated example sql query

---

docs/cms-hccs.md

Added high-level knowledge or MMR and MOR reports

added mmr and mor knowledge to cms-hccs

---

docs/risk-adjustment/cms-hccs.md

Adding more context around MMR slightly, not sure how much additional data is needed around this. @sarah-tuva , let me know if this is too little or too much detail that you were looking for around the MMR / MOR.

Updates to provide a little more data around the MMR

---

docs/risk-adjustment/cms-hccs.md

Adding in a little bit about the MAO-004 for risk adjustment.

Additional risk adjustment updates

---

docs/provider-data.md

Here are some suggestions to expand on the provider data page

Expansions to provider page

---

docs/claims-data-fundamentals/claims-dates.md
docs/claims-data-fundamentals/how-claims-are-paid.md
docs/welcome.md
sidebars.js

Added section on claims dates and video on common data quality issues that plague these fields.

added claims date section

---

docusaurus.config.js
src/css/custom.css

Added link to tuvahealth.com website to top right of site.

added tuva link

---

docs/claims-data-fundamentals/adjustments-denials-reversals.md

A few minor changes to the ADR explaination.

Adr updates

---

docs/data-dictionaries/readmissions.md

Updates to the readmissions data dictionary.

Readmissions dd

---

docs/data-dictionaries/input-layer.md

Add descriptions and toggles to input layer data dictionary.

Add documentation for the input layer

---

docs/connectors/overview.md
docs/data-dictionaries/core.md
docs/data-dictionaries/input-layer.md
docs/getting-started/introduction.md
docs/getting-started/quickstart.md
sidebars.js

Improvements:
- Data dictionaries
- Quickstart
- Connectors (added this)

Miscellaneous Updates

---

docs/reference-data.md

Fix links to reference data in S3 buckets.

Fix reference data links

---

docs/geo-coding.md

Update link to renamed github repo

Update geo-coding repo link

---

src/components/JsonDataTable.js

PR to add parsing of terminology_note metadata fields.

Terminology notes functionality add

---

docs/data-dictionaries/financial-pmpm.md

Resolves https://github.com/tuva-health/docs/issues/210.
* Added mart description.
* Added primary keys for each final table.
* Added missing final table, member_months.

Update data dictionary for Financial PMPM

---

docs/data-dictionaries/cms-hccs.md
docs/data-dictionaries/hcc-suspecting.md
sidebars.js

* Added data dictionary for hcc_suspecting
* Added table details to cms_hcc page

Add data dictionary for hcc_suspecting data mart

---

docs/data-dictionaries/hcc-suspecting.md

Updated final table names for HCC Suspecting mart.

Minor update to table names for HCC Suspecting

---

docs/data-dictionaries/hcc-suspecting.md
docs/terminology-sets.md

Updated terminology sets page (note: link will not work until PR merged in Tuva repo).
Updated hcc_suspecting page.

Add documentation for snomed_icd_10_map seed

---

docs/knowledge-base/risk-adjustment/overview.md

Fix typo in overview.md 

---

docs/data-dictionaries/hcc-suspecting.md
docs/terminology-sets.md

* Add terminology maintenance notes 
* Added guidance for default mapping logic to terminology and hcc_suspecting

Add more details to SNOMED to ICD Map terminology

---

docs/knowledge-base/risk-adjustment/cms-hccs.md

* Updated CMS HCC page with more details on the transition to v28
* Updated data mart overview

Update CMS HCC docs with v28 details

---

docs/guides/claims-mapping.md

As I was reading the claims mapping guide, I think I saw a minor typo. 
If I'm missing some additional context and this was intentional, please ignore! Thank you so much for writing the mapping guide! It was very helpful

Proposed change: Fix potential typo on claims mapping guide (institutional -> professional)

---

docs/use-cases/ed-visits.md

ed section update

---

docs/guides/claims-data/adr.md
docs/guides/claims-data/eligibility.md
docs/guides/claims-data/medical-claims.md

Update mapping guide with the latest tips and instructions.
- claim without eligibility
- mapping POS
- using claim start and end for admit and discharge
- mapping death date
- identifying reversals
- etc
https://www.loom.com/share/09845957dd7847ce882397c5b420935f?sid=f954f2df-6b2a-4ad4-bc3c-c6c298f3bfa0

Mapping Guide Updates

---

docs/data-marts/quality-measures.md

Updated the list of planned QMs.

Update Quality Measure page with additional planned measures

---

docs/use-cases/ahrq-measures.md
sidebars.js

ahrq use cases

---

docs/data-marts/quality-measures.md
docs/use-cases/cms-hccs.md

* Add new use-case for CMS HCC using new weighted risk score
* Update status for two new quality measures

Docs update for CMS HCC use-case and released Quality Measures

---

docs/connectors/cms-cclf.md

Add links to download CCLF sample synthetic data from the Tuva public S3 bucket.

Add links to download CCLF sample synthetic data

---

docs/data-marts/quality-measures.md

* Resolves #312 - added section headers and analytics queries
* Updated status of CQM48

Add new sections to Quality Measures

---

docs/data-marts/readmissions.md

Added documentation for the Readmissions data mart.

readmission mart documentation

---

docs/data-marts/chronic-conditions.md

Resolves #310 - added section headers and analytics queries

Add new sections to Chronic Conditions

---

docs/data-marts/cms-hccs.md
docs/data-marts/hcc-suspecting.md
docs/data-marts/quality-measures.md

* Add new sections and analytics to CMS HCC (resolves #307)
* Add new sections and analytics to HCC Suspecting (resolves #310 )
* Standardize sections for Quality Measures

Update HCC and Quality Measure pages

---

docs/data-marts/ahrq-measures.md
docs/data-marts/financial-pmpm.md
docs/guides/data-source-setup/mapping.md

* Add new sections and analytics to PMPM (resolves #309)
* Fix typo on AHRQ page
* Fix typo on data source mapping page

Update PMPM page

---

docs/data-marts/ed-classification.md

Add new sections and analytics to ED Classification (resolves #308)

Update ED Classification page

---

docs/data-marts/ccsr.md

Add new sections and analytics to ED Classification (resolves #304)

Update CCSR page

---

docs/guides/data-source-setup/customizations.md
docs/guides/data-source-setup/mapping.md
docs/guides/data-source-setup/union.md
docs/guides/data-source-setup/upgrades.md
sidebars.js

Mapping checklist for medical_claim and pharmacy_claim.

mapping checklist

---

docs/contributing/style-guide.md

Update the style guide with notes on Fabric SQL compatibility.

Update style guide with Fabric compatibility notes

---

docs/data-marts/hcc-suspecting.md

Added missing method (recapture) and organized methods on the HCC Suspecting data mart for clarity.

HCC Suspecting updates

---

docs/data-marts/encounter-types.md

add missing encounter types to docs

Update Encounter Documentation

---

docs/connectors/cms-cclf.md

Add new data prep instructions for using the connector.

Update CCLF connector page

---

docs/value-sets/service-categories.md

fixing service category latest file link

fixed link to service category file

---

docs/terminology/overview.md

In #378 I was running into some difficulty extracting compressed files hosted on Docs. I wanted to add a short section in case others are running into the same issue as I was. I believe this would close #378

Add Section to Terminology Overview for File Extraction errors

---

docs/connectors/canvas.md
sidebars.js

Adds docs for initial release of Canvas connector. closes #389

Add docs for canvas connector

---

docs/terminology/icd-10-cm.md
docusaurus.config.js

Resolves Issue #398 and updates ICD10 Termionology page with additional details.

added context  instructions for icd-10-cm terminology page

---

docs/connectors/cerner.md
sidebars.js

This PR adds docs on the Cerner connector.

Add docs on Cerner connector

---

docs/connectors/overview.md

links Cerner connector on overview page. closes #412

Add Cerner connector to Connectors Overview

---

docs/connectors/healthie.md
docs/connectors/overview.md
sidebars.js

This PR adds documentation for an early-release Healthie Connector.

Add docs on Healthie Connector

---

docs/data-marts/quality-measures.md

consolidate quality measures documentation to include knowledge article in mart section

consolidate quality measures docs

---

docs/community/manifesto.md

Fix typo in Manifesto

---

docs/analytics/overview.md
sidebars.js

numbers were off on sidebars so just a quick pr to fix

fix sidebar numbering

---

docs/predictive-models/risk-adjusted-benchmarking.md

changing available models to list prospective and concurrent

Prospective docs update
